services:
  - type: web
    name: crear-carpetas-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_CLIENT_SECRET_FILE
        sync: false
      - key: GOOGLE_TOKEN_FILE
        sync: false
      - key: SUPABASE_PROJECT_ID
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO

